name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Make image tag
      id: tag-name
      run: echo "DT=$(date +%s)" >> "$GITHUB_OUTPUT"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dshatz/kdedev:${{ steps.tag-name.outputs.DT }} --tag dshatz/kdedev:latest
    - name: Push to DockerHub
      run: docker push dshatz/kdedev:${{ steps.tag-name.outputs.DT }} && docker push dshatz/kdedev:latest
